version: '3.8'

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=f1db 
    networks:
      - pg-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"  
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    networks:
      - pg-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"  
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /home/carlos/f1/f1_analysis/f1_analysis/data:/app/data #Map cdlsol host directory to container directory
    depends_on:
      - pgdatabase
    ports:
      - "35603:35603"  
    networks:
      - pg-network
    restart: unless-stopped

volumes:
  pgdata:
  pgadmin_data:

networks:
  pg-network:
    driver: bridge
